ArNetworking: ArCentralManager Class Reference
ArCentralManager Class Reference
#include <ArCentralManager.h>
Public Member Functions
void addForwarderAddedCallback (ArFunctor1< ArCentralForwarder * > *functor, int priority=0)
Adds a callback for when a new forwarder is added.
void addForwarderRemovedCallback (ArFunctor1< ArCentralForwarder * > *functor, int priority=0)
Adds a callback for when a new forwarder is destroyed.
ArCentralManager (ArServerBase *robotServer, ArServerBase *clientServer)
Constructor.
void forwarderServerClientRemovedCallback (ArCentralForwarder *forwarder, ArServerClient *client)
A callback so we can tell the main connection happened when a client is removed.
void logConnections (void)
Logs all the connection information.
void mainServerClientRemovedCallback (ArServerClient *client)
A callback so we can close down other connetions when a main client loses connection.
void netClientList (ArServerClient *client, ArNetPacket *packet)
Networking command to get the list of clients.
void netServerSwitch (ArServerClient *client, ArNetPacket *packet)
Networking command to switch the direction of a connection.
void remForwarderAddedCallback (ArFunctor1< ArCentralForwarder * > *functor)
Removes a callback for when a new forwarder is added.
void remForwarderRemovedCallback (ArFunctor1< ArCentralForwarder * > *functor)
Removes a callback for when a new forwarder is destroyed.
virtual void * runThread (void *arg)
This should be its own thread here.
virtual ~ArCentralManager ()
Destructor.
Protected Member Functions
void close (void)
bool processFile (void)
Protected Attributes
ArFunctorC< ArCentralManager > myAriaExitCB
ArMutex myCallbackMutex
double myClientBackupTimeout
std::list< std::string > myClientNames
ArServerBase * myClientServer
std::list< ArSocket * > myClientSockets
ArTypes::UByte4 myClosingConnectionID
ArMutex myDataMutex
std::multimap< int, ArFunctor1
< ArCentralForwarder * > * > myForwarderAddedCBList
std::multimap< int, ArFunctor1
< ArCentralForwarder * > * > myForwarderRemovedCBList
std::list< ArCentralForwarder * > myForwarders
ArFunctor2C< ArCentralManager,
ArCentralForwarder
*, ArServerClient * > myForwarderServerClientRemovedCB
double myHeartbeatTimeout
ArFunctor1C< ArCentralManager,
ArServerClient * > myMainServerClientRemovedCB
int myMostClients
int myMostForwarders
ArFunctor2C< ArCentralManager,
ArServerClient *, ArNetPacket * > myNetClientListCB
ArFunctor2C< ArCentralManager,
ArServerClient *, ArNetPacket * > myNetSwitchCB
int myOnSocket
ArRetFunctorC< bool,
ArCentralManager > myProcessFileCB
double myRobotBackupTimeout
ArServerBase * myRobotServer
double myUdpHeartbeatTimeout
std::set< int > myUsedPorts
Constructor & Destructor Documentation
ArCentralManager::ArCentralManager (ArServerBase * robotServer, ArServerBase * clientServer)
Constructor.
References ArServerBase::addClientRemovedCallback(), ArServerBase::addData(), Aria::addExitCallback(), ArConfig::addParam(), ArConfig::addProcessFileCB(), ArPriority::DETAILED, Aria::getConfig(), myAriaExitCB, myClientBackupTimeout, myClientServer, myClosingConnectionID, myDataMutex, myForwarderServerClientRemovedCB, myHeartbeatTimeout, myMainServerClientRemovedCB, myMostClients, myMostForwarders, ArThread::myMutex, myNetClientListCB, myNetSwitchCB, myProcessFileCB, myRobotBackupTimeout, myRobotServer, myUdpHeartbeatTimeout, ArASyncTask::runAsync(), ArMutex::setLogName(), ArFunctor::setName(), and ArThread::setThreadName().
ArCentralManager::~ArCentralManager () [virtual]
Destructor.
Member Function Documentation
void ArCentralManager::addForwarderAddedCallback (ArFunctor1< ArCentralForwarder * > * functor, int priority = 0)
Adds a callback for when a new forwarder is added.
References ArMutex::lock(), myCallbackMutex, myForwarderAddedCBList, and ArMutex::unlock().
void ArCentralManager::addForwarderRemovedCallback (ArFunctor1< ArCentralForwarder * > * functor, int priority = 0)
Adds a callback for when a new forwarder is destroyed.
References ArMutex::lock(), myCallbackMutex, myForwarderRemovedCBList, and ArMutex::unlock().
void ArCentralManager::close (void) [protected]
References ArLog::log(), myForwarderRemovedCBList, myForwarders, and ArLog::Normal.
void ArCentralManager::forwarderServerClientRemovedCallback (ArCentralForwarder * forwarder, ArServerClient * client)
A callback so we can tell the main connection happened when a client is removed.
References ArServerBase::broadcastPacketTcpToMatching(), ArCentralForwarder::getClient(), ArServerClientIdentifier::getConnectionID(), ArServerClient::getIdentifier(), ArSocket::getIPString(), ArServerClient::getIPString(), ArCentralForwarder::getPort(), ArCentralForwarder::getRobotName(), ArClientBase::getTcpSocket(), ArLog::log(), myClientServer, myClosingConnectionID, and ArLog::Normal.
void ArCentralManager::logConnections (void)
Logs all the connection information.
References ArServerBase::getNumClients(), ArCentralForwarder::getRobotName(), ArCentralForwarder::getServer(), ArCentralForwarder::isConnected(), ArMutex::lock(), ArLog::log(), ArServerBase::logConnections(), myClientServer, myDataMutex, myForwarders, myMostClients, myMostForwarders, ArLog::Normal, and ArMutex::unlock().
void ArCentralManager::mainServerClientRemovedCallback (ArServerClient * client)
A callback so we can close down other connetions when a main client loses connection.
References ArServerBase::closeConnectionID(), ArServerClientIdentifier::getConnectionID(), ArServerClient::getIdentifier(), ArServerClient::getIPString(), ArCentralForwarder::getServer(), ArMutex::lock(), ArLog::log(), myClosingConnectionID, myDataMutex, myForwarders, ArLog::Normal, and ArMutex::unlock().
void ArCentralManager::netClientList (ArServerClient * client, ArNetPacket * packet)
Networking command to get the list of clients.
References ArCentralForwarder::getClient(), ArSocket::getIPString(), ArBasePacket::getLength(), ArCentralForwarder::getPort(), ArCentralForwarder::getRobotName(), ArClientBase::getTcpSocket(), ArCentralForwarder::isConnected(), ArMutex::lock(), myDataMutex, myForwarders, ArServerClient::sendPacketTcp(), ArBasePacket::setLength(), ArBasePacket::strToBuf(), ArBasePacket::uByte2ToBuf(), and ArMutex::unlock().
void ArCentralManager::netServerSwitch (ArServerClient * client, ArNetPacket * packet)
Networking command to switch the direction of a connection.
acknowledge the switch
References ArBasePacket::bufToStr(), ArServerClient::forceDisconnect(), ArServerClient::getIPString(), ArCentralForwarder::getRobotName(), ArServerClient::getTcpSocket(), ArMutex::lock(), ArLog::log(), myClientNames, myClientSockets, myDataMutex, myForwarders, ArLog::Normal, ArServerClient::sendPacketTcp(), ArServerClient::tcpCallback(), ArSocket::transfer(), and ArMutex::unlock().
bool ArCentralManager::processFile (void) [protected]
References myClientBackupTimeout, myClientServer, and ArServerBase::setBackupTimeout().
void ArCentralManager::remForwarderAddedCallback (ArFunctor1< ArCentralForwarder * > * functor)
Removes a callback for when a new forwarder is added.
References ArMutex::lock(), myCallbackMutex, myForwarderAddedCBList, and ArMutex::unlock().
void ArCentralManager::remForwarderRemovedCallback (ArFunctor1< ArCentralForwarder * > * functor)
Removes a callback for when a new forwarder is destroyed.
References ArMutex::lock(), myCallbackMutex, myForwarderRemovedCBList, and ArMutex::unlock().
void * ArCentralManager::runThread (void * arg) [virtual]
This should be its own thread here.
Implements ArASyncTask.
References ArServerBase::broadcastPacketTcp(), ArCentralForwarder::callOnce(), ArCentralForwarder::getClient(), ArSocket::getIPString(), ArServerBase::getNumClients(), ArCentralForwarder::getPort(), ArCentralForwarder::getRobotName(), ArThread::getRunning(), ArCentralForwarder::getServer(), ArServerBase::getTcpPort(), ArClientBase::getTcpSocket(), ArCentralForwarder::isConnected(), ArMutex::lock(), ArLog::log(), myClientBackupTimeout, myClientNames, myClientServer, myClientSockets, myDataMutex, myForwarderAddedCBList, myForwarderRemovedCBList, myForwarders, myForwarderServerClientRemovedCB, myHeartbeatTimeout, myMostClients, myMostForwarders, myRobotBackupTimeout, myRobotServer, myUdpHeartbeatTimeout, myUsedPorts, ArLog::Normal, ArUtil::sleep(), ArThread::threadFinished(), ArThread::threadStarted(), and ArMutex::unlock().
Member Data Documentation
ArFunctorC<ArCentralManager> ArCentralManager::myAriaExitCB [protected]
Referenced by ArCentralManager().
ArMutex ArCentralManager::myCallbackMutex [protected]
Referenced by addForwarderAddedCallback(), addForwarderRemovedCallback(), remForwarderAddedCallback(), and remForwarderRemovedCallback().
double ArCentralManager::myClientBackupTimeout [protected]
Referenced by ArCentralManager(), processFile(), and runThread().
std::list<std::string> ArCentralManager::myClientNames [protected]
Referenced by netServerSwitch(), and runThread().
ArServerBase* ArCentralManager::myClientServer [protected]
Referenced by ArCentralManager(), forwarderServerClientRemovedCallback(), logConnections(), processFile(), and runThread().
std::list<ArSocket *> ArCentralManager::myClientSockets [protected]
Referenced by netServerSwitch(), and runThread().
ArTypes::UByte4 ArCentralManager::myClosingConnectionID [protected]
Referenced by ArCentralManager(), forwarderServerClientRemovedCallback(), and mainServerClientRemovedCallback().
ArMutex ArCentralManager::myDataMutex [protected]
Referenced by ArCentralManager(), logConnections(), mainServerClientRemovedCallback(), netClientList(), netServerSwitch(), and runThread().
std::multimap<int, ArFunctor1<ArCentralForwarder *> *> ArCentralManager::myForwarderAddedCBList [protected]
Referenced by addForwarderAddedCallback(), remForwarderAddedCallback(), and runThread().
std::multimap<int, ArFunctor1<ArCentralForwarder *> *> ArCentralManager::myForwarderRemovedCBList [protected]
Referenced by addForwarderRemovedCallback(), close(), remForwarderRemovedCallback(), and runThread().
std::list<ArCentralForwarder *> ArCentralManager::myForwarders [protected]
Referenced by close(), logConnections(), mainServerClientRemovedCallback(), netClientList(), netServerSwitch(), and runThread().
ArFunctor2C<ArCentralManager, ArCentralForwarder *, ArServerClient *> ArCentralManager::myForwarderServerClientRemovedCB [protected]
Referenced by ArCentralManager(), and runThread().
double ArCentralManager::myHeartbeatTimeout [protected]
Referenced by ArCentralManager(), and runThread().
ArFunctor1C<ArCentralManager, ArServerClient *> ArCentralManager::myMainServerClientRemovedCB [protected]
Referenced by ArCentralManager().
int ArCentralManager::myMostClients [protected]
Referenced by ArCentralManager(), logConnections(), and runThread().
int ArCentralManager::myMostForwarders [protected]
Referenced by ArCentralManager(), logConnections(), and runThread().
ArFunctor2C<ArCentralManager, ArServerClient *, ArNetPacket *> ArCentralManager::myNetClientListCB [protected]
Referenced by ArCentralManager().
ArFunctor2C<ArCentralManager, ArServerClient *, ArNetPacket *> ArCentralManager::myNetSwitchCB [protected]
Referenced by ArCentralManager().
int ArCentralManager::myOnSocket [protected]
ArRetFunctorC<bool, ArCentralManager> ArCentralManager::myProcessFileCB [protected]
Referenced by ArCentralManager().
double ArCentralManager::myRobotBackupTimeout [protected]
Referenced by ArCentralManager(), and runThread().
ArServerBase* ArCentralManager::myRobotServer [protected]
Referenced by ArCentralManager(), and runThread().
double ArCentralManager::myUdpHeartbeatTimeout [protected]
Referenced by ArCentralManager(), and runThread().
std::set<int> ArCentralManager::myUsedPorts [protected]
Referenced by runThread().
The documentation for this class was generated from the following files:
ArCentralManager.h
ArCentralManager.cpp