ArNetworking: ArNetPacketSenderTcp Class Reference
ArNetPacketSenderTcp Class Reference
#include <ArNetPacketSenderTcp.h>
Public Member Functions
ArNetPacketSenderTcp ()
Constructor.
ArSocket * getSocket (void)
Gets the socket this sender uses.
bool sendData (void)
Tries to send the data there is to be sent.
void sendPacket (ArNetPacket *packet, const char *loggingString="")
Sends a packet.
void setBackupTimeout (double connectionTimeoutInMins)
Sets the connection timeout.
void setDebugLogging (bool debugLogging)
Sets debug logging.
void setLoggingPrefix (const char *prefix)
Sets the logging prefix.
void setSocket (ArSocket *socket)
Sets the socket this sender uses.
~ArNetPacketSenderTcp ()
Destructor.
Protected Attributes
int myAlreadySent
double myBackupTimeout
const char * myBuf
ArMutex myDataMutex
bool myDebugLogging
ArTime myLastGoodSend
int myLength
std::string myLoggingPrefix
ArNetPacket * myPacket
std::list< ArNetPacket * > myPacketList
ArSocket * mySocket
ArLog::LogLevel myVerboseLogLevel
Constructor & Destructor Documentation
ArNetPacketSenderTcp::ArNetPacketSenderTcp ()
Constructor.
References myBackupTimeout, myDataMutex, myLastGoodSend, setDebugLogging(), ArMutex::setLogName(), and ArTime::setToNow().
ArNetPacketSenderTcp::~ArNetPacketSenderTcp ()
Destructor.
References ArBasePacket::getLength(), ArLog::log(), myPacketList, and ArLog::Normal.
Member Function Documentation
ArSocket * ArNetPacketSenderTcp::getSocket (void)
Gets the socket this sender uses.
Gets the socket that the receiver is using, note that it does not have ownership of this socket and that whatever created it should.
References mySocket.
bool ArNetPacketSenderTcp::sendData (void)
Tries to send the data there is to be sent.
References ArNetPacket::getArbitraryString(), ArBasePacket::getBuf(), ArNetPacket::getCommand(), ArSocket::getIPString(), ArBasePacket::getLength(), ArMutex::lock(), ArLog::log(), ArNetPacket::MAX_LENGTH, myAlreadySent, myBackupTimeout, myBuf, myDataMutex, myDebugLogging, myLastGoodSend, myLength, myLoggingPrefix, myPacket, myPacketList, mySocket, myVerboseLogLevel, ArLog::Normal, ArTime::secSince(), ArTime::setToNow(), ArLog::Terse, ArMutex::unlock(), and ArSocket::write().
Referenced by ArClientBase::loopOnce(), ArServerClient::shutdown(), ArClientBase::startNonBlockingDisconnect(), and ArServerClient::tcpCallback().
void ArNetPacketSenderTcp::sendPacket (ArNetPacket * packet, const char * loggingString = "")
Sends a packet.
References ArNetPacket::duplicatePacket(), ArNetPacket::getCommand(), ArBasePacket::getLength(), ArMutex::lock(), myDataMutex, myDebugLogging, myPacketList, ArNetPacket::setArbitraryString(), and ArMutex::unlock().
Referenced by ArServerClient::sendPacketTcp(), and ArClientBase::sendPacketTcp().
void ArNetPacketSenderTcp::setBackupTimeout (double connectionTimeoutInMins)
Sets the connection timeout.
References myBackupTimeout.
Referenced by ArServerClient::setBackupTimeout(), and ArClientBase::setBackupTimeout().
void ArNetPacketSenderTcp::setDebugLogging (bool debugLogging)
Sets debug logging.
References myDebugLogging, myVerboseLogLevel, ArLog::Normal, and ArLog::Verbose.
Referenced by ArClientBase::ArClientBase(), ArNetPacketSenderTcp(), and ArServerClient::ArServerClient().
void ArNetPacketSenderTcp::setLoggingPrefix (const char * prefix)
Sets the logging prefix.
References myLoggingPrefix.
Referenced by ArServerClient::ArServerClient(), and ArClientBase::setRobotName().
void ArNetPacketSenderTcp::setSocket (ArSocket * socket)
Sets the socket this sender uses.
Sets the socket that this receiver will use, note that it does not transfer ownership of the socket.
Parameters:
socket the socket to use for receiving data
References ArMutex::lock(), myDataMutex, mySocket, and ArMutex::unlock().
Referenced by ArClientBase::ArClientBase(), and ArServerClient::ArServerClient().
Member Data Documentation
int ArNetPacketSenderTcp::myAlreadySent [protected]
Referenced by sendData().
double ArNetPacketSenderTcp::myBackupTimeout [protected]
Referenced by ArNetPacketSenderTcp(), sendData(), and setBackupTimeout().
const char* ArNetPacketSenderTcp::myBuf [protected]
Referenced by sendData().
ArMutex ArNetPacketSenderTcp::myDataMutex [protected]
Referenced by ArNetPacketSenderTcp(), sendData(), sendPacket(), and setSocket().
bool ArNetPacketSenderTcp::myDebugLogging [protected]
Referenced by sendData(), sendPacket(), and setDebugLogging().
ArTime ArNetPacketSenderTcp::myLastGoodSend [protected]
Referenced by ArNetPacketSenderTcp(), and sendData().
int ArNetPacketSenderTcp::myLength [protected]
Referenced by sendData().
std::string ArNetPacketSenderTcp::myLoggingPrefix [protected]
Referenced by sendData(), and setLoggingPrefix().
ArNetPacket* ArNetPacketSenderTcp::myPacket [protected]
Referenced by sendData().
std::list<ArNetPacket *> ArNetPacketSenderTcp::myPacketList [protected]
Referenced by sendData(), sendPacket(), and ~ArNetPacketSenderTcp().
ArSocket* ArNetPacketSenderTcp::mySocket [protected]
Referenced by getSocket(), sendData(), and setSocket().
ArLog::LogLevel ArNetPacketSenderTcp::myVerboseLogLevel [protected]
Referenced by sendData(), and setDebugLogging().
The documentation for this class was generated from the following files:
ArNetPacketSenderTcp.h
ArNetPacketSenderTcp.cpp