ArNetworking: ArServerClientData Class Reference
ArServerClientData Class Reference
#include <ArServerClientData.h>
Public Member Functions
ArServerClientData (ArServerData *serverData, long mSecInterval, ArNetPacket *packet)
ArTime getLastSent (void)
long getMSec (void)
ArNetPacket * getPacket (void)
ArServerData * getServerData (void)
void setLastSentToNow (void)
void setMSec (long mSec)
void setPacket (ArNetPacket *packet)
virtual ~ArServerClientData ()
Protected Attributes
ArTime myLastSent
long myMSecInterval
ArNetPacket myPacket
unsigned int myReadLength
ArServerData * myServerData
Constructor & Destructor Documentation
ArServerClientData::ArServerClientData (ArServerData * serverData, long mSecInterval, ArNetPacket * packet) [inline]
References ArNetPacket::duplicatePacket(), ArBasePacket::getReadLength(), myLastSent, myMSecInterval, myPacket, myReadLength, myServerData, and ArTime::setToNow().
virtual ArServerClientData::~ArServerClientData () [inline, virtual]
Member Function Documentation
ArTime ArServerClientData::getLastSent (void) [inline]
References myLastSent.
Referenced by ArServerClient::handleRequests().
long ArServerClientData::getMSec (void) [inline]
References myMSecInterval.
Referenced by ArServerClient::getFrequency(), and ArServerClient::handleRequests().
ArNetPacket* ArServerClientData::getPacket (void) [inline]
References myPacket, myReadLength, and ArBasePacket::setReadLength().
Referenced by ArServerClient::handleRequests(), and ArServerClient::processPacket().
ArServerData* ArServerClientData::getServerData (void) [inline]
References myServerData.
Referenced by ArServerClient::broadcastPacketTcp(), ArServerClient::broadcastPacketUdp(), ArServerClient::getFrequency(), ArServerClient::handleRequests(), and ArServerClient::processPacket().
void ArServerClientData::setLastSentToNow (void) [inline]
References myLastSent, and ArTime::setToNow().
Referenced by ArServerClient::handleRequests().
void ArServerClientData::setMSec (long mSec) [inline]
References myMSecInterval.
Referenced by ArServerClient::processPacket().
void ArServerClientData::setPacket (ArNetPacket * packet) [inline]
References ArNetPacket::duplicatePacket(), ArBasePacket::getReadLength(), myPacket, and myReadLength.
Referenced by ArServerClient::processPacket().
Member Data Documentation
ArTime ArServerClientData::myLastSent [protected]
Referenced by ArServerClientData(), getLastSent(), and setLastSentToNow().
long ArServerClientData::myMSecInterval [protected]
Referenced by ArServerClientData(), getMSec(), and setMSec().
ArNetPacket ArServerClientData::myPacket [protected]
Referenced by ArServerClientData(), getPacket(), and setPacket().
unsigned int ArServerClientData::myReadLength [protected]
Referenced by ArServerClientData(), getPacket(), and setPacket().
ArServerData* ArServerClientData::myServerData [protected]
Referenced by ArServerClientData(), and getServerData().
The documentation for this class was generated from the following file:
ArServerClientData.h