ArNetworking: ArServerSimpleServerCommands Class Reference
ArServerSimpleServerCommands Class Reference
#include <ArServerSimpleCommands.h>
Detailed Description
Examples:
serverDemo.cpp.
Public Member Functions
ArServerSimpleServerCommands (ArServerHandlerCommands *commands, ArServerBase *server, bool addLogConnections=true)
void logConnections (void)
void logTerseTracking (void)
void logVerboseTracking (void)
void resetTracking (void)
virtual ~ArServerSimpleServerCommands ()
Constructor & Destructor Documentation
ArServerSimpleServerCommands::ArServerSimpleServerCommands (ArServerHandlerCommands * commands, ArServerBase * server, bool addLogConnections = true)
References ArServerHandlerCommands::addCommand().
ArServerSimpleServerCommands::~ArServerSimpleServerCommands () [virtual]
Member Function Documentation
void ArServerSimpleServerCommands::logConnections (void)
References ArServerBase::logConnections().
void ArServerSimpleServerCommands::logTerseTracking (void)
References ArServerBase::logTracking().
void ArServerSimpleServerCommands::logVerboseTracking (void)
References ArServerBase::logTracking().
void ArServerSimpleServerCommands::resetTracking (void)
References ArServerBase::resetTracking().
The documentation for this class was generated from the following files:
ArServerSimpleCommands.h
ArServerSimpleCommands.cpp