ArNetworking: OutputHandler Class Reference
OutputHandler Class Reference
Detailed Description
This class requests continual data updates from the server and prints them out.
Public Member Functions
void handleBatteryInfo (ArNetPacket *packet)
This callback is called when an update on the battery configuration changes.
void handleOutput (ArNetPacket *packet)
This callback is called when an update on general robot state arrives.
void handleOutputNumbers (ArNetPacket *packet)
This callback is called when an update on general robot state arrives.
void handleOutputStrings (ArNetPacket *packet)
This callback is called when an update on general robot state arrives.
void handlePhysicalInfo (ArNetPacket *packet)
This is called when the physical robot information comes back.
void handleTemperatureInfo (ArNetPacket *packet)
This callback is called when an update on the temperature information changes.
OutputHandler (ArClientBase *client)
virtual ~OutputHandler (void)
Protected Attributes
ArClientBase * myClient
bool myGotBatteryInfo
Don't print any information until we get the battery info.
bool myNeedToPrintHeader
A header for the columns in the data printout is sometimes printed.
ArFunctor1C< OutputHandler,
ArNetPacket * > myHandleBatteryInfoCB
ArFunctor1C< OutputHandler,
ArNetPacket * > myHandleOutputCB
These functor objects are given to the client to receive updates when they arrive from the server.
ArFunctor1C< OutputHandler,
ArNetPacket * > myHandleOutputNumbersCB
ArFunctor1C< OutputHandler,
ArNetPacket * > myHandleOutputStringsCB
ArFunctor1C< OutputHandler,
ArNetPacket * > myHandlePhysicalInfoCB
ArFunctor1C< OutputHandler,
ArNetPacket * > myHandleTemperatureInfoCB
double myLatVel
char myMode [256]
double myRotVel
char myStatus [256]
char myTemperature
double myTh
double myVel
double myVoltage
bool myVoltageIsStateOfCharge
double myX
The results from the data update are stored in these variables.
double myY
Constructor & Destructor Documentation
OutputHandler::OutputHandler (ArClientBase * client)
References ArClientBase::addHandler(), ArClientBase::dataExists(), myClient, myHandleBatteryInfoCB, myHandleOutputCB, myHandleOutputNumbersCB, myHandleOutputStringsCB, myHandlePhysicalInfoCB, myHandleTemperatureInfoCB, ArClientBase::request(), and ArClientBase::requestOnce().
OutputHandler::~OutputHandler (void) [virtual]
References myClient, and ArClientBase::requestStop().
Member Function Documentation
void OutputHandler::handleBatteryInfo (ArNetPacket * packet)
This callback is called when an update on the battery configuration changes.
References ArNetPacket::bufToDouble(), ArBasePacket::bufToUByte(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), myGotBatteryInfo, myNeedToPrintHeader, and myVoltageIsStateOfCharge.
void OutputHandler::handleOutput (ArNetPacket * packet)
This callback is called when an update on general robot state arrives.
References ArBasePacket::bufToByte(), ArBasePacket::bufToByte2(), ArBasePacket::bufToByte4(), ArBasePacket::bufToStr(), myGotBatteryInfo, myLatVel, myMode, myNeedToPrintHeader, myRotVel, myStatus, myTemperature, myTh, myVel, myVoltage, myVoltageIsStateOfCharge, myX, and myY.
void OutputHandler::handleOutputNumbers (ArNetPacket * packet)
This callback is called when an update on general robot state arrives.
References ArBasePacket::bufToByte(), ArBasePacket::bufToByte2(), ArBasePacket::bufToByte4(), myGotBatteryInfo, myLatVel, myMode, myNeedToPrintHeader, myRotVel, myStatus, myTemperature, myTh, myVel, myVoltage, myVoltageIsStateOfCharge, myX, and myY.
void OutputHandler::handleOutputStrings (ArNetPacket * packet)
This callback is called when an update on general robot state arrives.
References ArBasePacket::bufToStr(), myMode, and myStatus.
void OutputHandler::handlePhysicalInfo (ArNetPacket * packet)
This is called when the physical robot information comes back.
References ArBasePacket::bufToByte2(), and ArBasePacket::bufToStr().
void OutputHandler::handleTemperatureInfo (ArNetPacket * packet)
This callback is called when an update on the temperature information changes.
References ArBasePacket::bufToByte(), and myNeedToPrintHeader.
Member Data Documentation
ArClientBase* OutputHandler::myClient [protected]
Referenced by OutputHandler(), and ~OutputHandler().
bool OutputHandler::myGotBatteryInfo [protected]
Don't print any information until we get the battery info.
Referenced by handleBatteryInfo(), handleOutput(), and handleOutputNumbers().
ArFunctor1C<OutputHandler, ArNetPacket *> OutputHandler::myHandleBatteryInfoCB [protected]
Referenced by OutputHandler().
ArFunctor1C<OutputHandler, ArNetPacket *> OutputHandler::myHandleOutputCB [protected]
These functor objects are given to the client to receive updates when they arrive from the server.
Referenced by OutputHandler().
ArFunctor1C<OutputHandler, ArNetPacket *> OutputHandler::myHandleOutputNumbersCB [protected]
Referenced by OutputHandler().
ArFunctor1C<OutputHandler, ArNetPacket *> OutputHandler::myHandleOutputStringsCB [protected]
Referenced by OutputHandler().
ArFunctor1C<OutputHandler, ArNetPacket *> OutputHandler::myHandlePhysicalInfoCB [protected]
Referenced by OutputHandler().
ArFunctor1C<OutputHandler, ArNetPacket *> OutputHandler::myHandleTemperatureInfoCB [protected]
Referenced by OutputHandler().
double OutputHandler::myLatVel [protected]
Referenced by handleOutput(), and handleOutputNumbers().
char OutputHandler::myMode[256] [protected]
Referenced by handleOutput(), handleOutputNumbers(), and handleOutputStrings().
bool OutputHandler::myNeedToPrintHeader [protected]
A header for the columns in the data printout is sometimes printed.
Referenced by handleBatteryInfo(), handleOutput(), handleOutputNumbers(), and handleTemperatureInfo().
double OutputHandler::myRotVel [protected]
Referenced by handleOutput(), and handleOutputNumbers().
char OutputHandler::myStatus[256] [protected]
Referenced by handleOutput(), handleOutputNumbers(), and handleOutputStrings().
char OutputHandler::myTemperature [protected]
Referenced by handleOutput(), and handleOutputNumbers().
double OutputHandler::myTh [protected]
Referenced by handleOutput(), and handleOutputNumbers().
double OutputHandler::myVel [protected]
Referenced by handleOutput(), and handleOutputNumbers().
double OutputHandler::myVoltage [protected]
Referenced by handleOutput(), and handleOutputNumbers().
bool OutputHandler::myVoltageIsStateOfCharge [protected]
Referenced by handleBatteryInfo(), handleOutput(), and handleOutputNumbers().
double OutputHandler::myX [protected]
The results from the data update are stored in these variables.
Referenced by handleOutput(), and handleOutputNumbers().
double OutputHandler::myY [protected]
Referenced by handleOutput(), and handleOutputNumbers().
The documentation for this class was generated from the following file:
clientDemo.cpp