ArNetworking: ArClientHandlerConfig Class Reference
ArClientHandlerConfig Class Reference
#include <ArClientHandlerConfig.h>
Detailed Description
Client handler for receiving and updating ArConfig data via ArNetworking.
ArClientHandlerConfig processes the network packets that describe a robot's ArConfig. It also provides a means to save the modified configuration data to the robot server. This class is designed to work in conjunction with the ArServerHandlerConfig. See the server handler documentation for a complete description of the networking interface.
This class should be thread safe, with the exception of unThreadSafeGetConfig. (If you want to use this method, surround it with calls to lock() and unlock().)
Note that you can't add callbacks or remove callbacks from within a callback function.
Public Member Functions
void addGotConfigCB (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a gotConfig callback.
void addGotConfigDefaultsCB (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a got config defaults callback.
void addSaveConfigFailedCB (ArFunctor1< const char * > *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a save config to server failed callback.
void addSaveConfigSucceededCB (ArFunctor *functor, ArListPos::Pos position=ArListPos::LAST)
Adds a save config to server succeeded callback.
ArClientHandlerConfig (ArClientBase *client, bool ignoreBounds=false, const char *robotName=NULL)
Constructor.
bool canRequestDefaults (void)
Sees if we can request defaults (both types).
ArConfig * getConfig (void)
Unthreadsafe way to get the config to play with (see long docs).
ArConfig getConfigCopy (void)
Threadsafe way to get the config to play with.
ArConfig * getDefaultConfig ()
Returns a pointer to the robot server's default configuration, if canRequestDefaults() is true.
void handleGetConfig (ArNetPacket *packet)
Handles the packet from the getConfig.
void handleGetConfigBySections (ArNetPacket *packet)
Handles the packet from the GetConfigBySections.
void handleGetConfigDefaults (ArNetPacket *packet)
Handles the return packet from getConfigDefaults.
void handleGetConfigSectionFlags (ArNetPacket *packet)
Handles the packet from the GetConfigSectionFlags.
void handleSetConfig (ArNetPacket *packet)
Handles the return packet from the setConfig (saveConfigToServer).
bool haveGottenConfig (void)
Returns true if config gotten.
bool haveGottenDefaults (void)
Returns if we've gotten our requested defaults.
bool haveRequestedDefaults (void)
Returns if we've requested some defaults.
int lock (void)
Locks the config for if you're using the unthreadsafe getConfig.
void reloadConfigOnServer (void)
Tells the server to reload the configuration.
void remGotConfigCB (ArFunctor *functor)
Removes a gotConfig callback.
void remGotConfigDefaultsCB (ArFunctor *functor)
Removes a got config defaults callback.
void remSaveConfigFailedCB (ArFunctor1< const char * > *functor)
Removes a save config to server failed callback.
void remSaveConfigSucceededCB (ArFunctor *functor)
Removes a save config to server succeeded callback.
bool requestConfigDefaults (void)
Requests defaults for all sections from the server; modifies the config.
void requestConfigFromServer (void)
Requests the config from the server.
bool requestDefaultConfigFromServer (void)
bool requestSectionDefaults (const char *section)
Requests defaults for one section from the server; modifies the config.
void saveConfigToServer (ArConfig *config, const std::set< std::string, ArStrCaseCmpOp > *ignoreTheseSections=NULL)
Sends the config back to the server.
void saveConfigToServer (void)
Sends the config back to the server.
void setQuiet (bool isQuiet)
Turn on this flag to reduce the number of verbose log messages.
int tryLock (void)
Try to lock for the config for if you're using the unthreadsafe getConfig.
int unlock (void)
Unlocks the config for if you're using the unthreadsafe getConfig.
virtual ~ArClientHandlerConfig (void)
Destructor.
Protected Member Functions
void handleGetConfigData (ArNetPacket *packet, bool isMultiplePackets)
Protected Attributes
ArMutex myCallbackMutex
ArClientBase * myClient
ArConfig myConfig
ArMutex myDataMutex
ArConfig * myDefaultConfig
std::list< ArFunctor * > myGotConfigCBList
std::list< ArFunctor * > myGotConfigDefaultsCBList
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigBySectionsCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigDefaultsCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetConfigSectionFlagsCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleGetDefaultConfigCB
ArFunctor1C
< ArClientHandlerConfig,
ArNetPacket * > myHandleSetConfigCB
bool myHaveGottenConfig
bool myHaveGottenDefaults
bool myHaveRequestedDefaultCopy
bool myHaveRequestedDefaults
bool myIsQuiet
std::string myLogPrefix
std::string myRobotName
std::list< ArFunctor1< const
char * > * > mySaveConfigFailedCBList
std::list< ArFunctor * > mySaveConfigSucceededCBList
Constructor & Destructor Documentation
ArClientHandlerConfig::ArClientHandlerConfig (ArClientBase * client, bool ignoreBounds = false, const char * robotName = NULL)
Constructor.
Parameters:
client the client base to attach to
ignoreBounds whether the ArConfig we have should ignore bounds or not, this should only be used for debugging
robotName a name or identifier for the robot the server is controlling, used for logging etc.
References myCallbackMutex, myClient, myConfig, myDataMutex, myHaveGottenConfig, myHaveGottenDefaults, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, myIsQuiet, myLogPrefix, myRobotName, ArConfig::setConfigName(), and ArMutex::setLogName().
ArClientHandlerConfig::~ArClientHandlerConfig (void) [virtual]
Destructor.
References myDefaultConfig.
Member Function Documentation
void ArClientHandlerConfig::addGotConfigCB (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a gotConfig callback.
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, myGotConfigCBList, ArLog::Terse, and ArMutex::unlock().
Referenced by main().
void ArClientHandlerConfig::addGotConfigDefaultsCB (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a got config defaults callback.
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, myGotConfigDefaultsCBList, ArLog::Terse, and ArMutex::unlock().
void ArClientHandlerConfig::addSaveConfigFailedCB (ArFunctor1< const char * > * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a save config to server failed callback.
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, mySaveConfigFailedCBList, ArLog::Terse, and ArMutex::unlock().
Referenced by main().
void ArClientHandlerConfig::addSaveConfigSucceededCB (ArFunctor * functor, ArListPos::Pos position = ArListPos::LAST)
Adds a save config to server succeeded callback.
References ArListPos::FIRST, ArListPos::LAST, ArMutex::lock(), ArLog::log(), myCallbackMutex, mySaveConfigSucceededCBList, ArLog::Terse, and ArMutex::unlock().
Referenced by main().
bool ArClientHandlerConfig::canRequestDefaults (void)
Sees if we can request defaults (both types).
References ArClientBase::dataExists(), and myClient.
Referenced by main(), requestConfigDefaults(), requestDefaultConfigFromServer(), and requestSectionDefaults().
ArConfig * ArClientHandlerConfig::getConfig (void)
Unthreadsafe way to get the config to play with (see long docs).
This will get the config, note, it gets the config we're using, so if you change something while data comes in things will get broken.
References myConfig.
Referenced by gotConfig().
ArConfig ArClientHandlerConfig::getConfigCopy (void)
Threadsafe way to get the config to play with.
This will get a copy of the config, you can use this with the safeConfigToServer that takes an argument.
References ArMutex::lock(), myConfig, myDataMutex, and ArMutex::unlock().
ArConfig * ArClientHandlerConfig::getDefaultConfig (void)
Returns a pointer to the robot server's default configuration, if canRequestDefaults() is true.
Note that both requestConfigFromServer() and then requestDefaultConfigFromServer() must be called before a valid default configuration is available on the client. If there is no default configuration, then NULL is returned.
References myDefaultConfig.
Referenced by main().
void ArClientHandlerConfig::handleGetConfig (ArNetPacket * packet)
Handles the packet from the getConfig.
References handleGetConfigData().
void ArClientHandlerConfig::handleGetConfigBySections (ArNetPacket * packet)
Handles the packet from the GetConfigBySections.
References handleGetConfigData().
void ArClientHandlerConfig::handleGetConfigData (ArNetPacket * packet, bool isMultiplePackets) [protected]
References ArConfig::addParam(), ArBasePacket::bufToByte(), ArBasePacket::bufToStr(), ArClientArg::createArg(), ArConfigArg::getConfigPriority(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), ArConfigArg::getDisplayHint(), IFDEBUG, ArPriority::LAST_PRIORITY, ArMutex::lock(), ArConfig::log(), ArLog::log(), myCallbackMutex, myConfig, myDataMutex, myGotConfigCBList, myHaveGottenConfig, myLogPrefix, ArLog::Normal, ArConfig::setSectionComment(), ArLog::Terse, ArMutex::unlock(), and ArLog::Verbose.
Referenced by handleGetConfig(), and handleGetConfigBySections().
void ArClientHandlerConfig::handleGetConfigDefaults (ArNetPacket * packet)
Handles the return packet from getConfigDefaults.
References ArArgumentBuilder::add(), ArBasePacket::bufToStr(), ArConfig::clearAllValueSet(), ArBasePacket::getDataLength(), ArBasePacket::getDataReadLength(), IFDEBUG, ArMutex::lock(), ArConfig::log(), ArLog::log(), myCallbackMutex, myConfig, myDataMutex, myDefaultConfig, myGotConfigDefaultsCBList, myHaveGottenDefaults, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, myIsQuiet, myLogPrefix, myRobotName, ArLog::Normal, ArConfig::parseArgument(), ArConfig::parseSection(), ArConfig::removeAllUnsetValues(), ArConfig::setConfigName(), ArArgumentBuilder::setExtraString(), ArArgumentBuilder::setQuiet(), ArConfig::setQuiet(), ArLog::Terse, and ArMutex::unlock().
void ArClientHandlerConfig::handleGetConfigSectionFlags (ArNetPacket * packet)
Handles the packet from the GetConfigSectionFlags.
References ArConfig::addSectionFlags(), ArBasePacket::bufToByte4(), ArBasePacket::bufToStr(), ArMutex::lock(), myConfig, myDataMutex, and ArMutex::unlock().
void ArClientHandlerConfig::handleSetConfig (ArNetPacket * packet)
Handles the return packet from the setConfig (saveConfigToServer).
References ArBasePacket::bufToStr(), ArMutex::lock(), ArLog::log(), myCallbackMutex, myLogPrefix, mySaveConfigFailedCBList, mySaveConfigSucceededCBList, ArLog::Normal, and ArMutex::unlock().
bool ArClientHandlerConfig::haveGottenConfig (void)
Returns true if config gotten.
References ArMutex::lock(), myDataMutex, myHaveGottenConfig, and ArMutex::unlock().
bool ArClientHandlerConfig::haveGottenDefaults (void)
Returns if we've gotten our requested defaults.
References ArMutex::lock(), myDataMutex, myHaveGottenDefaults, and ArMutex::unlock().
Referenced by main().
bool ArClientHandlerConfig::haveRequestedDefaults (void)
Returns if we've requested some defaults.
References ArMutex::lock(), myDataMutex, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, and ArMutex::unlock().
Referenced by requestConfigDefaults(), requestDefaultConfigFromServer(), and requestSectionDefaults().
int ArClientHandlerConfig::lock (void)
Locks the config for if you're using the unthreadsafe getConfig.
References ArMutex::lock(), and myDataMutex.
void ArClientHandlerConfig::reloadConfigOnServer (void)
Tells the server to reload the configuration.
References myClient, and ArClientBase::requestOnce().
void ArClientHandlerConfig::remGotConfigCB (ArFunctor * functor)
Removes a gotConfig callback.
References ArMutex::lock(), myCallbackMutex, myGotConfigCBList, and ArMutex::unlock().
void ArClientHandlerConfig::remGotConfigDefaultsCB (ArFunctor * functor)
Removes a got config defaults callback.
References ArMutex::lock(), myCallbackMutex, myGotConfigDefaultsCBList, and ArMutex::unlock().
void ArClientHandlerConfig::remSaveConfigFailedCB (ArFunctor1< const char * > * functor)
Removes a save config to server failed callback.
References ArMutex::lock(), myCallbackMutex, mySaveConfigFailedCBList, and ArMutex::unlock().
void ArClientHandlerConfig::remSaveConfigSucceededCB (ArFunctor * functor)
Removes a save config to server succeeded callback.
References ArMutex::lock(), myCallbackMutex, mySaveConfigSucceededCBList, and ArMutex::unlock().
bool ArClientHandlerConfig::requestConfigDefaults (void)
Requests defaults for all sections from the server; modifies the config.
References canRequestDefaults(), haveRequestedDefaults(), ArMutex::lock(), ArLog::log(), myClient, myDataMutex, myHaveGottenDefaults, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, myLogPrefix, ArLog::Normal, ArClientBase::requestOnce(), and ArMutex::unlock().
void ArClientHandlerConfig::requestConfigFromServer (void)
Requests the config from the server.
This requests a config from the server and resets it so we haven't gotten a config.
References ArClientBase::addHandler(), ArConfig::clearSections(), ArClientBase::dataExists(), ArPriority::LAST_PRIORITY, ArMutex::lock(), ArLog::log(), myClient, myConfig, myDataMutex, myHandleGetConfigBySectionsCB, myHandleGetConfigCB, myHandleGetConfigDefaultsCB, myHandleGetConfigSectionFlagsCB, myHandleSetConfigCB, myHaveGottenConfig, myLogPrefix, ArClientBase::remHandler(), ArClientBase::requestOnce(), ArMutex::unlock(), and ArLog::Verbose.
Referenced by main().
bool ArClientHandlerConfig::requestDefaultConfigFromServer (void)
References canRequestDefaults(), haveRequestedDefaults(), ArMutex::lock(), ArLog::log(), myClient, myDataMutex, myHaveGottenDefaults, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, myLogPrefix, ArLog::Normal, ArClientBase::requestOnce(), and ArMutex::unlock().
Referenced by main().
bool ArClientHandlerConfig::requestSectionDefaults (const char * section)
Requests defaults for one section from the server; modifies the config.
References canRequestDefaults(), ArConfig::findSection(), haveRequestedDefaults(), ArMutex::lock(), ArLog::log(), myClient, myConfig, myDataMutex, myHaveGottenDefaults, myHaveRequestedDefaultCopy, myHaveRequestedDefaults, myLogPrefix, ArLog::Normal, ArClientBase::requestOnceWithString(), and ArMutex::unlock().
void ArClientHandlerConfig::saveConfigToServer (ArConfig * config, const std::set< std::string, ArStrCaseCmpOp > * ignoreTheseSections = NULL)
Sends the config back to the server.
References ArClientArg::argTextToBuf(), ArConfigArg::getName(), ArConfigSection::getName(), ArConfigSection::getParams(), ArConfig::getSections(), ArClientArg::isSendableParamType(), ArMutex::lock(), ArLog::log(), myClient, myDataMutex, myLogPrefix, ArLog::Normal, ArClientBase::requestOnce(), ArBasePacket::strToBuf(), ArMutex::unlock(), and ArLog::Verbose.
void ArClientHandlerConfig::saveConfigToServer (void)
Sends the config back to the server.
References myConfig.
Referenced by gotConfig().
void ArClientHandlerConfig::setQuiet (bool isQuiet)
Turn on this flag to reduce the number of verbose log messages.
References myConfig, myDefaultConfig, myIsQuiet, and ArConfig::setQuiet().
int ArClientHandlerConfig::tryLock (void)
Try to lock for the config for if you're using the unthreadsafe getConfig.
References myDataMutex, and ArMutex::tryLock().
int ArClientHandlerConfig::unlock (void)
Unlocks the config for if you're using the unthreadsafe getConfig.
References myDataMutex, and ArMutex::unlock().
Member Data Documentation
ArMutex ArClientHandlerConfig::myCallbackMutex [protected]
Referenced by addGotConfigCB(), addGotConfigDefaultsCB(), addSaveConfigFailedCB(), addSaveConfigSucceededCB(), ArClientHandlerConfig(), handleGetConfigData(), handleGetConfigDefaults(), handleSetConfig(), remGotConfigCB(), remGotConfigDefaultsCB(), remSaveConfigFailedCB(), and remSaveConfigSucceededCB().
ArClientBase* ArClientHandlerConfig::myClient [protected]
Referenced by ArClientHandlerConfig(), canRequestDefaults(), reloadConfigOnServer(), requestConfigDefaults(), requestConfigFromServer(), requestDefaultConfigFromServer(), requestSectionDefaults(), and saveConfigToServer().
ArConfig ArClientHandlerConfig::myConfig [protected]
Referenced by ArClientHandlerConfig(), getConfig(), getConfigCopy(), handleGetConfigData(), handleGetConfigDefaults(), handleGetConfigSectionFlags(), requestConfigFromServer(), requestSectionDefaults(), saveConfigToServer(), and setQuiet().
ArMutex ArClientHandlerConfig::myDataMutex [protected]
Referenced by ArClientHandlerConfig(), getConfigCopy(), handleGetConfigData(), handleGetConfigDefaults(), handleGetConfigSectionFlags(), haveGottenConfig(), haveGottenDefaults(), haveRequestedDefaults(), lock(), requestConfigDefaults(), requestConfigFromServer(), requestDefaultConfigFromServer(), requestSectionDefaults(), saveConfigToServer(), tryLock(), and unlock().
ArConfig* ArClientHandlerConfig::myDefaultConfig [protected]
Referenced by getDefaultConfig(), handleGetConfigDefaults(), setQuiet(), and ~ArClientHandlerConfig().
std::list<ArFunctor *> ArClientHandlerConfig::myGotConfigCBList [protected]
Referenced by addGotConfigCB(), handleGetConfigData(), and remGotConfigCB().
std::list<ArFunctor *> ArClientHandlerConfig::myGotConfigDefaultsCBList [protected]
Referenced by addGotConfigDefaultsCB(), handleGetConfigDefaults(), and remGotConfigDefaultsCB().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigBySectionsCB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigCB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigDefaultsCB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetConfigSectionFlagsCB [protected]
Referenced by requestConfigFromServer().
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleGetDefaultConfigCB [protected]
ArFunctor1C<ArClientHandlerConfig, ArNetPacket *> ArClientHandlerConfig::myHandleSetConfigCB [protected]
Referenced by requestConfigFromServer().
bool ArClientHandlerConfig::myHaveGottenConfig [protected]
Referenced by ArClientHandlerConfig(), handleGetConfigData(), haveGottenConfig(), and requestConfigFromServer().
bool ArClientHandlerConfig::myHaveGottenDefaults [protected]
Referenced by ArClientHandlerConfig(), handleGetConfigDefaults(), haveGottenDefaults(), requestConfigDefaults(), requestDefaultConfigFromServer(), and requestSectionDefaults().
bool ArClientHandlerConfig::myHaveRequestedDefaultCopy [protected]
Referenced by ArClientHandlerConfig(), handleGetConfigDefaults(), haveRequestedDefaults(), requestConfigDefaults(), requestDefaultConfigFromServer(), and requestSectionDefaults().
bool ArClientHandlerConfig::myHaveRequestedDefaults [protected]
Referenced by ArClientHandlerConfig(), handleGetConfigDefaults(), haveRequestedDefaults(), requestConfigDefaults(), requestDefaultConfigFromServer(), and requestSectionDefaults().
bool ArClientHandlerConfig::myIsQuiet [protected]
Referenced by ArClientHandlerConfig(), handleGetConfigDefaults(), and setQuiet().
std::string ArClientHandlerConfig::myLogPrefix [protected]
Referenced by ArClientHandlerConfig(), handleGetConfigData(), handleGetConfigDefaults(), handleSetConfig(), requestConfigDefaults(), requestConfigFromServer(), requestDefaultConfigFromServer(), requestSectionDefaults(), and saveConfigToServer().
std::string ArClientHandlerConfig::myRobotName [protected]
Referenced by ArClientHandlerConfig(), and handleGetConfigDefaults().
std::list<ArFunctor1<const char *> *> ArClientHandlerConfig::mySaveConfigFailedCBList [protected]
Referenced by addSaveConfigFailedCB(), handleSetConfig(), and remSaveConfigFailedCB().
std::list<ArFunctor *> ArClientHandlerConfig::mySaveConfigSucceededCBList [protected]
Referenced by addSaveConfigSucceededCB(), handleSetConfig(), and remSaveConfigSucceededCB().
The documentation for this class was generated from the following files:
ArClientHandlerConfig.h
ArClientHandlerConfig.cpp