ArNetworking: clientCommandLister.cpp File Reference
clientCommandLister.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Examples:
drawingsExample.cpp, drawingsExampleWithRobot.cpp, getVideoExample.cpp, popupExample.cpp, ptzCameraClientExample.cpp, serverDemo.cpp, and simpleServerExample.cpp.
References ArArgumentParser::checkHelpAndWarnUnparsed(), client, ArClientSimpleConnector::connectClient(), ArClientBase::getHost(), ArLog::init(), Aria::init(), ArArgumentParser::loadDefaultArguments(), ArClientBase::logDataList(), ArClientSimpleConnector::logOptions(), ArLog::Normal, ArClientSimpleConnector::parseArgs(), ArClientBase::runAsync(), ArClientBase::setRobotName(), Aria::shutdown(), ArUtil::sleep(), ArLog::StdOut, and ArClientBase::wasRejected().