ArNetworking: configClient.cpp File Reference
configClient.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
Functions
void gotConfig (void)
int main (int argc, char **argv)
Variables
ArClientBase * client
ArClientHandlerConfig * configHandler
bool done = false
Function Documentation
void gotConfig (void)
References done, ArClientHandlerConfig::getConfig(), and ArConfig::writeFile().
Referenced by main().
int main (int argc, char ** argv)
References ArClientHandlerConfig::addGotConfigCB(), ArClientHandlerConfig::canRequestDefaults(), ArArgumentParser::checkHelpAndWarnUnparsed(), ArClientSimpleConnector::connectClient(), done, Aria::exit(), ArClientHandlerConfig::getDefaultConfig(), ArClientBase::getHost(), gotConfig(), ArClientHandlerConfig::haveGottenDefaults(), Aria::init(), ArArgumentParser::loadDefaultArguments(), Aria::logOptions(), Aria::parseArgs(), ArClientHandlerConfig::requestConfigFromServer(), ArClientHandlerConfig::requestDefaultConfigFromServer(), ArClientBase::runAsync(), ArClientBase::setRobotName(), ArUtil::sleep(), and ArConfig::writeFile().
Variable Documentation
ArClientBase* client
Examples:
drawingsExample.cpp, drawingsExampleWithRobot.cpp, getVideoExample.cpp, and ptzCameraClientExample.cpp.
Referenced by ArServerBase::close(), ArServerBase::closeConnectionID(), ArServerBase::finishAcceptingSocket(), ArServerBase::logConnections(), ArServerBase::loopOnce(), main(), ArServerBase::processPacket(), and ArServerBase::slowIdleCallback().
ArClientHandlerConfig* configHandler
Referenced by main().
bool done = false
Referenced by gotConfig(), main(), and ArClientFileFromClient::netPutFile().