ArNetworking: configServer.cpp File Reference
configServer.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References ArConfig::addParam(), configHandler, Aria::getConfig(), ArPriority::IMPORTANT, Aria::init(), ArPriority::NORMAL, ArServerBase::open(), ArConfig::parseFile(), ArServerBase::run(), ArConfig::setBaseDirectory(), ArConfig::setSectionComment(), Aria::shutdown(), ArPriority::TRIVIAL, and ArConfig::writeFile().