ArNetworking: drawingsExample.cpp File Reference
drawingsExample.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
#include <math.h>
Classes
class Circle
Functions
void exampleArrowsDrawingNetCallback (ArServerClient *client, ArNetPacket *requestPkt)
void exampleDotsDrawingNetCallback (ArServerClient *client, ArNetPacket *requestPkt)
void exampleHomeDrawingNetCallback (ArServerClient *client, ArNetPacket *requestPkt)
void exampleXDrawingNetCallback (ArServerClient *client, ArNetPacket *requestPkt)
int main (int argc, char **argv)
Function Documentation
void exampleArrowsDrawingNetCallback (ArServerClient * client, ArNetPacket * requestPkt)
Examples:
drawingsExample.cpp, and drawingsExampleWithRobot.cpp.
References ArBasePacket::byte4ToBuf(), and ArServerClient::sendPacketUdp().
Referenced by main().
void exampleDotsDrawingNetCallback (ArServerClient * client, ArNetPacket * requestPkt)
Examples:
drawingsExample.cpp, and drawingsExampleWithRobot.cpp.
References ArBasePacket::byte4ToBuf(), ArUtil::getTime(), and ArServerClient::sendPacketUdp().
Referenced by main().
void exampleHomeDrawingNetCallback (ArServerClient * client, ArNetPacket * requestPkt)
Examples:
drawingsExample.cpp, and drawingsExampleWithRobot.cpp.
References ArBasePacket::byte4ToBuf(), and ArServerClient::sendPacketUdp().
Referenced by main().
void exampleXDrawingNetCallback (ArServerClient * client, ArNetPacket * requestPkt)
Examples:
drawingsExample.cpp, and drawingsExampleWithRobot.cpp.
References ArBasePacket::byte4ToBuf(), and ArServerClient::sendPacketUdp().
Referenced by main().
int main (int argc, char ** argv)
References ArServerInfoDrawings::addDrawing(), ArServerSimpleOpener::checkAndLog(), ArArgumentParser::checkHelpAndWarnUnparsed(), exampleArrowsDrawingNetCallback(), exampleDotsDrawingNetCallback(), exampleHomeDrawingNetCallback(), exampleXDrawingNetCallback(), Aria::getKeyHandler(), Aria::init(), ArArgumentParser::loadDefaultArguments(), ArServerSimpleOpener::logOptions(), ArServerSimpleOpener::open(), ArServerSimpleOpener::parseArgs(), ArServerBase::runAsync(), Aria::setKeyHandler(), Circle::setNumPoints(), Circle::setPos(), Circle::setRadius(), Aria::shutdown(), ArUtil::sleep(), and ArServerSimpleOpener::wasUserFileBad().