ArNetworking: serverDemo.cpp File Reference
serverDemo.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References ArServerModeStop::activate(), ArStringInfoGroup::addAddStringCallback(), ArServerMode::addAsDefaultMode(), ArCameraCollection::addCamera(), ArUtil::addDirectories(), ArRobot::addRangeDevice(), ArServerInfoDrawings::addRobotsRangeDevices(), ArStringInfoGroup::addStringInt(), ArLog::addToConfig(), ArRobot::attachKeyHandler(), ArServerSimpleOpener::checkAndLog(), ArArgumentParser::checkHelpAndWarnUnparsed(), ArLaserConnector::connectLasers(), ArRobotConnector::connectRobot(), ArRobot::enableMotors(), Aria::exit(), ArServerInfoStrings::getAddStringFunctor(), Aria::getConfig(), Aria::getDirectory(), Aria::getInfoGroup(), Aria::getKeyHandler(), ArRobot::getMotorPacCount(), ArPTZ::init(), Aria::init(), ArHybridForwarderVideo::isForwardingVideo(), ArArgumentParser::loadDefaultArguments(), ArRobot::lock(), Aria::logOptions(), ArServerSimpleOpener::open(), Aria::parseArgs(), ArASyncTask::runAsync(), ArServerBase::runAsync(), ArRobot::runAsync(), Aria::setKeyHandler(), ArRobot::unlock(), ArRobot::waitForRunExit(), and ArServerSimpleOpener::wasUserFileBad().