ArNetworking: simpleServerExample.cpp File Reference
simpleServerExample.cpp File Reference
#include "Aria.h"
#include "ArNetworking.h"
Functions
void customCommandHandler (ArArgumentBuilder *args)
int main (int argc, char **argv)
Function Documentation
void customCommandHandler (ArArgumentBuilder * args)
Examples:
simpleServerExample.cpp.
References ArArgumentBuilder::getArg(), ArLog::log(), and ArLog::Normal.
Referenced by main().
int main (int argc, char ** argv)
References ArServerModeStop::activate(), ArStringInfoGroup::addAddStringCallback(), ArServerMode::addAsDefaultMode(), ArServerModeRatioDrive::addControlCommands(), ArServerHandlerCommands::addStringCommand(), ArStringInfoGroup::addStringInt(), ArServerSimpleOpener::checkAndLog(), ArArgumentParser::checkHelpAndWarnUnparsed(), ArSimpleConnector::connectRobot(), customCommandHandler(), ArRobot::enableMotors(), ArServerInfoStrings::getAddStringFunctor(), Aria::getInfoGroup(), ArRobot::getMotorPacCount(), ArServerSimpleOpener::getPort(), Aria::init(), ArArgumentParser::loadDefaultArguments(), ArLog::log(), ArServerSimpleOpener::logOptions(), ArSimpleConnector::logOptions(), ArLog::Normal, ArServerSimpleOpener::open(), ArServerSimpleOpener::parseArgs(), ArSimpleConnector::parseArgs(), ArServerBase::runAsync(), ArRobot::runAsync(), Aria::shutdown(), ArLog::Terse, and ArRobot::waitForRunExit().